Script started on Tue 21 Nov 2017 08:17:46 PM PST
]0;jerrl10@zuma:~/hw4[jerrl10@zuma ~/hw4]$ make
gcc -Wall -ansi -std=c99 -c   Test.c -o Test.o
gcc -Wall -ansi -std=c99 -c   DIPs.c -o DIPs.o
gcc -Wall -ansi -std=c99 -c   Advanced.c -o Advanced.o
ar rc libfilter.a DIPs.o Advanced.o
ranlib libfilter.a
gcc -Wall -ansi -std=c99 -c   -g -DDEBUG FileIO.c -o FileIO.o
gcc -Wall -ansi -std=c99 -c   PhotoLab.c -o PhotoLab.o
gcc -Wall -ansi -std=c99 -c   Image.c -o Image.o
gcc -Wall -ansi -std=c99 -g -DDEBUG  Test.o FileIO.o PhotoLab.o Image.o -lfilter -L. -o PhotoLab
gcc -Wall -ansi -std=c99 -c  -g -DDEBUG Test.c -o TestAuto.o
gcc -Wall -ansi -std=c99 -c  -g -DDEBUG PhotoLab.c -o PhotoLabTest.o
gcc -Wall -ansi -std=c99 TestAuto.o FileIO.o DIPs.o Advanced.o PhotoLabTest.o Image.o -o PhotoLabTest
]0;jerrl10@zuma:~/hw4[jerrl10@zuma ~/hw4]$ ./
PhotoLab*     PhotoLabTest* 
]0;jerrl10@zuma:~/hw4[jerrl10@zuma ~/hw4]$ ./PhotoLab

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add noise to an image
12: Sharpen an image
13: Posterize an image
14: Blur an image
15: Crop an image
16: Resize an image
17: Adjust the Brightness and Contrast of an image
18: Add Watermark to an image
19: Test all functions
20: Exit
Please make your choice: 19
HSSOE.ppm was read successfully!
bw.ppm was saved successfully. 
bw.jpg was stored for viewing. 
HSSOE.ppm was read successfully!
negative.ppm was saved successfully. 
negative.jpg was stored for viewing. 
HSSOE.ppm was read successfully!
colorfilter.ppm was saved successfully. 
colorfilter.jpg was stored for viewing. 
HSSOE.ppm was read successfully!
edge.ppm was saved successfully. 
edge.jpg was stored for viewing. 
HSSOE.ppm was read successfully!
"Shuffle" operation is done!
shuffle.ppm was saved successfully. 
shuffle.jpg was stored for viewing. 
HSSOE.ppm was read successfully!
vflip.ppm was saved successfully. 
vflip.jpg was stored for viewing. 
HSSOE.ppm was read successfully!
vmirror.ppm was saved successfully. 
vmirror.jpg was stored for viewing. 
HSSOE.ppm was read successfully!
border.ppm was saved successfully. 
border.jpg was stored for viewing. 
HSSOE.ppm was read successfully!
noise.ppm was saved successfully. 
noise.jpg was stored for viewing. 
HSSOE.ppm was read successfully!
sharpen.ppm was saved successfully. 
sharpen.jpg was stored for viewing. 
HSSOE.ppm was read successfully!
posterize.ppm was saved successfully. 
posterize.jpg was stored for viewing. 
HSSOE.ppm was read successfully!
blur.ppm was saved successfully. 
blur.jpg was stored for viewing. 
HSSOE.ppm was read successfully!
crop.ppm was saved successfully. 
crop.jpg was stored for viewing. 
HSSOE.ppm was read successfully!
smallresize.ppm was saved successfully. 
smallresize.jpg was stored for viewing. 
HSSOE.ppm was read successfully!
bigresize.ppm was saved successfully. 
bigresize.jpg was stored for viewing. 
HSSOE.ppm was read successfully!
brightnessandcontrast.ppm was saved successfully. 
brightnessandcontrast.jpg was stored for viewing. 
HSSOE.ppm was read successfully!
watermark_template.ppm was read successfully!
watermark.ppm was saved successfully. 
watermark.jpg was stored for viewing. 
AutoTest finished successfully.

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add noise to an image
12: Sharpen an image
13: Posterize an image
14: Blur an image
15: Crop an image
16: Resize an image
17: Adjust the Brightness and Contrast of an image
18: Add Watermark to an image
19: Test all functions
20: Exit
Please make your choice: 20
You exit the program.
]0;jerrl10@zuma:~/hw4[jerrl10@zuma ~/hw4]$ valgrind --leak-check=full ./PhotoLabTest
==34474== Memcheck, a memory error detector
==34474== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==34474== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==34474== Command: ./PhotoLabTest
==34474== 
HSSOE.ppm was read successfully!
bw.ppm was saved successfully. 
bw.jpg was stored for viewing. 
Black and White tested!

HSSOE.ppm was read successfully!
negative.ppm was saved successfully. 
negative.jpg was stored for viewing. 
Negative tested!

HSSOE.ppm was read successfully!
colorfilter.ppm was saved successfully. 
colorfilter.jpg was stored for viewing. 
Color Filter tested!

HSSOE.ppm was read successfully!
edge.ppm was saved successfully. 
edge.jpg was stored for viewing. 
Edge Detection tested!

HSSOE.ppm was read successfully!
"Shuffle" operation is done!
shuffle.ppm was saved successfully. 
shuffle.jpg was stored for viewing. 
Shuffle tested!

HSSOE.ppm was read successfully!
vflip.ppm was saved successfully. 
vflip.jpg was stored for viewing. 
VFlip tested!

HSSOE.ppm was read successfully!
vmirror.ppm was saved successfully. 
vmirror.jpg was stored for viewing. 
VMirror tested!

HSSOE.ppm was read successfully!
border.ppm was saved successfully. 
border.jpg was stored for viewing. 
Add Border tested!

HSSOE.ppm was read successfully!
noise.ppm was saved successfully. 
noise.jpg was stored for viewing. 
Add Noise tested!

HSSOE.ppm was read successfully!
sharpen.ppm was saved successfully. 
sharpen.jpg was stored for viewing. 
Sharpen tested!

HSSOE.ppm was read successfully!
posterize.ppm was saved successfully. 
posterize.jpg was stored for viewing. 
Posterize tested!

HSSOE.ppm was read successfully!
blur.ppm was saved successfully. 
blur.jpg was stored for viewing. 
MotionBlur tested!

HSSOE.ppm was read successfully!
crop.ppm was saved successfully. 
crop.jpg was stored for viewing. 
Crop tested!

HSSOE.ppm was read successfully!
smallresize.ppm was saved successfully. 
smallresize.jpg was stored for viewing. 
HSSOE.ppm was read successfully!
bigresize.ppm was saved successfully. 
bigresize.jpg was stored for viewing. 
Resize tested!

HSSOE.ppm was read successfully!
brightnessandcontrast.ppm was saved successfully. 
brightnessandcontrast.jpg was stored for viewing. 
Brightness and Contrast tested!

HSSOE.ppm was read successfully!
watermark_template.ppm was read successfully!
watermark.ppm was saved successfully. 
watermark.jpg was stored for viewing. 
Watermark tested!

==34474== 
==34474== HEAP SUMMARY:
==34474==     in use at exit: 0 bytes in 0 blocks
==34474==   total heap usage: 135 allocs, 135 frees, 18,124,103 bytes allocated
==34474== 
==34474== All heap blocks were freed -- no leaks are possible
==34474== 
==34474== For counts of detected and suppressed errors, rerun with: -v
==34474== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)
]0;jerrl10@zuma:~/hw4[jerrl10@zuma ~/hw4]$ make clean
rm -f bw.ppm
rm -f negative.ppm
rm -f colorfilter.ppm
rm -f edge.ppm
rm -f shuffle.ppm
rm -f vflip.ppm
rm -f vmirror.ppm
rm -f border.ppm
rm -f noise.ppm
rm -f sharpen.ppm
rm -f posterize.ppm
rm -f blur.ppm
rm -f smallresize.ppm
rm -f bigresize.ppm
rm -f crop.ppm
rm -f brightnessandcontrast.ppm
rm -f watermark.ppm
rm -f *.o
rm -f PhotoLab
rm -f PhotoLabTest
]0;jerrl10@zuma:~/hw4[jerrl10@zuma ~/hw4]$ exit
exit

Script done on Tue 21 Nov 2017 08:19:29 PM PST
